### ISSUE TITLE
Crowdsource Translations

### ISSUE THREAD

**Issue by SandiyosDev** [temtan/bmx2wav#2]
Is it possible to implement a locale file for community translation?
It'll eliminate the garbled text problems, and the program will reach users across the world in creating better BMS tracks.

**Comment by temtan** [comment]
bmx2wav 内の日本語メッセージをリソースにして、多言語化が出来るようにすることを考慮していますが、正直面倒ですね。
でも、この要望があったので対応する方向で行きます。けど、気長に待って頂きたいですね。

I am considering using the Japanese message in bmx2wav as a resource to enable multilingualization, but honestly it is Bothersome.
However, since there was this request, I will go in the direction of responding. However, I would like you to wait patiently.

**Comment by SandiyosDev** [comment]
Yep, thanks for the consideration and time. 
Good work :D

**Comment by SandiyosDev** [comment]
Hey Temtan, I've been following your blog when you started working on it since early May, and you mentioned that the project is near completion.
I understand that this localization project was a tedious and bothersome project, but I and others in the future will definitely appreciate the work that you've put in.
Thanks again!
